# Generated by Django 5.2.12 on 2026-03-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loan_created_at_loanpayment_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestdistribution',
            options={'ordering': ['-distributed_at']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='savingsplan',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username']},
        ),
    ]
