# Generated by Django 5.2.12 on 2026-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_interestdistribution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
