# Generated by Django 5.2.1 on 2026-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_savings_plan_goal_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijcgroup',
            name='custom_interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ijcgroup',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ijcgroup',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ijcgroup',
            name='cash_out_policy',
            field=models.CharField(choices=[('DAILY', 'Daily Release'), ('WEEKLY', 'Weekly Release'), ('MONTHLY', 'Monthly Release'), ('CUSTOM', 'Custom Release')], default='WEEKLY', max_length=10),
        ),
    ]
