# Generated by Django 5.2.1 on 2026-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ijcgroup_custom_interval_days_ijcgroup_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijcgroup',
            name='pause_duration_seconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ijcgroup',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ijcgroup',
            name='release_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
