# Generated by Django on 2026-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ijcgroup_pause_duration_seconds_ijcgroup_paused_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijcgroup',
            name='pocket_type',
            field=models.CharField(choices=[('SPONSORED', 'Sponsored Pocket'), ('SELF', 'Self Pocket')], default='SPONSORED', max_length=10),
        ),
    ]
